/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type ApplicationId = bigint;
export interface ApplicationPublic {
  'id' : ApplicationId,
  'status' : ApplicationStatus,
  'appliedAt' : Timestamp,
  'applicantId' : UserId,
  'jobId' : JobId,
  'coverLetter' : string,
}
export type ApplicationStatus = { 'Viewed' : null } |
  { 'Rejected' : null } |
  { 'Accepted' : null } |
  { 'Pending' : null };
export interface CreateJobInput {
  'title' : string,
  'jobType' : JobType,
  'description' : string,
  'salaryMax' : bigint,
  'salaryMin' : bigint,
  'requiredSkills' : string,
  'location' : string,
}
export interface EmployerProfilePublic {
  'id' : UserId,
  'websiteUrl' : string,
  'createdAt' : Timestamp,
  'description' : string,
  'companyName' : string,
}
export type JobId = bigint;
export interface JobPublic {
  'id' : JobId,
  'status' : JobStatus,
  'title' : string,
  'postedAt' : Timestamp,
  'jobType' : JobType,
  'description' : string,
  'employerId' : UserId,
  'salaryMax' : bigint,
  'salaryMin' : bigint,
  'requiredSkills' : string,
  'location' : string,
}
export interface JobSeekerProfilePublic {
  'id' : UserId,
  'bio' : string,
  'yearsOfExperience' : bigint,
  'name' : string,
  'createdAt' : Timestamp,
  'email' : string,
  'phone' : string,
  'skills' : string,
}
export type JobStatus = { 'Open' : null } |
  { 'Closed' : null };
export type JobType = { 'PartTime' : null } |
  { 'Remote' : null } |
  { 'FullTime' : null };
export interface SubmitApplicationInput {
  'jobId' : JobId,
  'coverLetter' : string,
}
export type Timestamp = bigint;
export interface UpdateJobInput {
  'id' : JobId,
  'title' : string,
  'jobType' : JobType,
  'description' : string,
  'salaryMax' : bigint,
  'salaryMin' : bigint,
  'requiredSkills' : string,
  'location' : string,
}
export interface UpsertEmployerInput {
  'websiteUrl' : string,
  'description' : string,
  'companyName' : string,
}
export interface UpsertJobSeekerInput {
  'bio' : string,
  'yearsOfExperience' : bigint,
  'name' : string,
  'email' : string,
  'phone' : string,
  'skills' : string,
}
export type UserId = Principal;
export type UserType = { 'JobSeeker' : null } |
  { 'Employer' : null };
export interface _SERVICE {
  'adminGetStats' : ActorMethod<
    [],
    {
      'totalEmployers' : bigint,
      'totalJobSeekers' : bigint,
      'totalJobs' : bigint,
      'totalApplications' : bigint,
    }
  >,
  'adminListEmployers' : ActorMethod<[], Array<EmployerProfilePublic>>,
  'adminListJobSeekers' : ActorMethod<[], Array<JobSeekerProfilePublic>>,
  'createJob' : ActorMethod<[CreateJobInput], JobId>,
  'deleteJob' : ActorMethod<[JobId], undefined>,
  'getEmployerProfile' : ActorMethod<[UserId], [] | [EmployerProfilePublic]>,
  'getJob' : ActorMethod<[JobId], [] | [JobPublic]>,
  'getJobSeekerProfile' : ActorMethod<[UserId], [] | [JobSeekerProfilePublic]>,
  'getMyEmployerProfile' : ActorMethod<[], [] | [EmployerProfilePublic]>,
  'getMyJobSeekerProfile' : ActorMethod<[], [] | [JobSeekerProfilePublic]>,
  'getMyUserType' : ActorMethod<[], [] | [UserType]>,
  'getUserType' : ActorMethod<[UserId], [] | [UserType]>,
  'hasApplied' : ActorMethod<[JobId], boolean>,
  'listApplicationsForJob' : ActorMethod<[JobId], Array<ApplicationPublic>>,
  'listApplicationsForMyJobs' : ActorMethod<[], Array<ApplicationPublic>>,
  'listMyApplications' : ActorMethod<[], Array<ApplicationPublic>>,
  'listMyJobs' : ActorMethod<[], Array<JobPublic>>,
  'listOpenJobs' : ActorMethod<[], Array<JobPublic>>,
  'setUserType' : ActorMethod<[UserType], undefined>,
  'submitApplication' : ActorMethod<[SubmitApplicationInput], ApplicationId>,
  'toggleJobStatus' : ActorMethod<[JobId], undefined>,
  'updateApplicationStatus' : ActorMethod<
    [ApplicationId, ApplicationStatus],
    undefined
  >,
  'updateJob' : ActorMethod<[UpdateJobInput], undefined>,
  'upsertEmployerProfile' : ActorMethod<[UpsertEmployerInput], undefined>,
  'upsertJobSeekerProfile' : ActorMethod<[UpsertJobSeekerInput], undefined>,
  'withdrawApplication' : ActorMethod<[ApplicationId], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];