/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserId = IDL.Principal;
export const Timestamp = IDL.Int;
export const EmployerProfilePublic = IDL.Record({
  'id' : UserId,
  'websiteUrl' : IDL.Text,
  'createdAt' : Timestamp,
  'description' : IDL.Text,
  'companyName' : IDL.Text,
});
export const JobSeekerProfilePublic = IDL.Record({
  'id' : UserId,
  'bio' : IDL.Text,
  'yearsOfExperience' : IDL.Nat,
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'email' : IDL.Text,
  'phone' : IDL.Text,
  'skills' : IDL.Text,
});
export const JobType = IDL.Variant({
  'PartTime' : IDL.Null,
  'Remote' : IDL.Null,
  'FullTime' : IDL.Null,
});
export const CreateJobInput = IDL.Record({
  'title' : IDL.Text,
  'jobType' : JobType,
  'description' : IDL.Text,
  'salaryMax' : IDL.Nat,
  'salaryMin' : IDL.Nat,
  'requiredSkills' : IDL.Text,
  'location' : IDL.Text,
});
export const JobId = IDL.Nat;
export const JobStatus = IDL.Variant({
  'Open' : IDL.Null,
  'Closed' : IDL.Null,
});
export const JobPublic = IDL.Record({
  'id' : JobId,
  'status' : JobStatus,
  'title' : IDL.Text,
  'postedAt' : Timestamp,
  'jobType' : JobType,
  'description' : IDL.Text,
  'employerId' : UserId,
  'salaryMax' : IDL.Nat,
  'salaryMin' : IDL.Nat,
  'requiredSkills' : IDL.Text,
  'location' : IDL.Text,
});
export const UserType = IDL.Variant({
  'JobSeeker' : IDL.Null,
  'Employer' : IDL.Null,
});
export const ApplicationId = IDL.Nat;
export const ApplicationStatus = IDL.Variant({
  'Viewed' : IDL.Null,
  'Rejected' : IDL.Null,
  'Accepted' : IDL.Null,
  'Pending' : IDL.Null,
});
export const ApplicationPublic = IDL.Record({
  'id' : ApplicationId,
  'status' : ApplicationStatus,
  'appliedAt' : Timestamp,
  'applicantId' : UserId,
  'jobId' : JobId,
  'coverLetter' : IDL.Text,
});
export const SubmitApplicationInput = IDL.Record({
  'jobId' : JobId,
  'coverLetter' : IDL.Text,
});
export const UpdateJobInput = IDL.Record({
  'id' : JobId,
  'title' : IDL.Text,
  'jobType' : JobType,
  'description' : IDL.Text,
  'salaryMax' : IDL.Nat,
  'salaryMin' : IDL.Nat,
  'requiredSkills' : IDL.Text,
  'location' : IDL.Text,
});
export const UpsertEmployerInput = IDL.Record({
  'websiteUrl' : IDL.Text,
  'description' : IDL.Text,
  'companyName' : IDL.Text,
});
export const UpsertJobSeekerInput = IDL.Record({
  'bio' : IDL.Text,
  'yearsOfExperience' : IDL.Nat,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'phone' : IDL.Text,
  'skills' : IDL.Text,
});

export const idlService = IDL.Service({
  'adminGetStats' : IDL.Func(
      [],
      [
        IDL.Record({
          'totalEmployers' : IDL.Nat,
          'totalJobSeekers' : IDL.Nat,
          'totalJobs' : IDL.Nat,
          'totalApplications' : IDL.Nat,
        }),
      ],
      [],
    ),
  'adminListEmployers' : IDL.Func([], [IDL.Vec(EmployerProfilePublic)], []),
  'adminListJobSeekers' : IDL.Func([], [IDL.Vec(JobSeekerProfilePublic)], []),
  'createJob' : IDL.Func([CreateJobInput], [JobId], []),
  'deleteJob' : IDL.Func([JobId], [], []),
  'getEmployerProfile' : IDL.Func(
      [UserId],
      [IDL.Opt(EmployerProfilePublic)],
      ['query'],
    ),
  'getJob' : IDL.Func([JobId], [IDL.Opt(JobPublic)], ['query']),
  'getJobSeekerProfile' : IDL.Func(
      [UserId],
      [IDL.Opt(JobSeekerProfilePublic)],
      ['query'],
    ),
  'getMyEmployerProfile' : IDL.Func(
      [],
      [IDL.Opt(EmployerProfilePublic)],
      ['query'],
    ),
  'getMyJobSeekerProfile' : IDL.Func(
      [],
      [IDL.Opt(JobSeekerProfilePublic)],
      ['query'],
    ),
  'getMyUserType' : IDL.Func([], [IDL.Opt(UserType)], ['query']),
  'getUserType' : IDL.Func([UserId], [IDL.Opt(UserType)], ['query']),
  'hasApplied' : IDL.Func([JobId], [IDL.Bool], ['query']),
  'listApplicationsForJob' : IDL.Func(
      [JobId],
      [IDL.Vec(ApplicationPublic)],
      ['query'],
    ),
  'listApplicationsForMyJobs' : IDL.Func(
      [],
      [IDL.Vec(ApplicationPublic)],
      ['query'],
    ),
  'listMyApplications' : IDL.Func([], [IDL.Vec(ApplicationPublic)], ['query']),
  'listMyJobs' : IDL.Func([], [IDL.Vec(JobPublic)], ['query']),
  'listOpenJobs' : IDL.Func([], [IDL.Vec(JobPublic)], ['query']),
  'setUserType' : IDL.Func([UserType], [], []),
  'submitApplication' : IDL.Func([SubmitApplicationInput], [ApplicationId], []),
  'toggleJobStatus' : IDL.Func([JobId], [], []),
  'updateApplicationStatus' : IDL.Func(
      [ApplicationId, ApplicationStatus],
      [],
      [],
    ),
  'updateJob' : IDL.Func([UpdateJobInput], [], []),
  'upsertEmployerProfile' : IDL.Func([UpsertEmployerInput], [], []),
  'upsertJobSeekerProfile' : IDL.Func([UpsertJobSeekerInput], [], []),
  'withdrawApplication' : IDL.Func([ApplicationId], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserId = IDL.Principal;
  const Timestamp = IDL.Int;
  const EmployerProfilePublic = IDL.Record({
    'id' : UserId,
    'websiteUrl' : IDL.Text,
    'createdAt' : Timestamp,
    'description' : IDL.Text,
    'companyName' : IDL.Text,
  });
  const JobSeekerProfilePublic = IDL.Record({
    'id' : UserId,
    'bio' : IDL.Text,
    'yearsOfExperience' : IDL.Nat,
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'email' : IDL.Text,
    'phone' : IDL.Text,
    'skills' : IDL.Text,
  });
  const JobType = IDL.Variant({
    'PartTime' : IDL.Null,
    'Remote' : IDL.Null,
    'FullTime' : IDL.Null,
  });
  const CreateJobInput = IDL.Record({
    'title' : IDL.Text,
    'jobType' : JobType,
    'description' : IDL.Text,
    'salaryMax' : IDL.Nat,
    'salaryMin' : IDL.Nat,
    'requiredSkills' : IDL.Text,
    'location' : IDL.Text,
  });
  const JobId = IDL.Nat;
  const JobStatus = IDL.Variant({ 'Open' : IDL.Null, 'Closed' : IDL.Null });
  const JobPublic = IDL.Record({
    'id' : JobId,
    'status' : JobStatus,
    'title' : IDL.Text,
    'postedAt' : Timestamp,
    'jobType' : JobType,
    'description' : IDL.Text,
    'employerId' : UserId,
    'salaryMax' : IDL.Nat,
    'salaryMin' : IDL.Nat,
    'requiredSkills' : IDL.Text,
    'location' : IDL.Text,
  });
  const UserType = IDL.Variant({
    'JobSeeker' : IDL.Null,
    'Employer' : IDL.Null,
  });
  const ApplicationId = IDL.Nat;
  const ApplicationStatus = IDL.Variant({
    'Viewed' : IDL.Null,
    'Rejected' : IDL.Null,
    'Accepted' : IDL.Null,
    'Pending' : IDL.Null,
  });
  const ApplicationPublic = IDL.Record({
    'id' : ApplicationId,
    'status' : ApplicationStatus,
    'appliedAt' : Timestamp,
    'applicantId' : UserId,
    'jobId' : JobId,
    'coverLetter' : IDL.Text,
  });
  const SubmitApplicationInput = IDL.Record({
    'jobId' : JobId,
    'coverLetter' : IDL.Text,
  });
  const UpdateJobInput = IDL.Record({
    'id' : JobId,
    'title' : IDL.Text,
    'jobType' : JobType,
    'description' : IDL.Text,
    'salaryMax' : IDL.Nat,
    'salaryMin' : IDL.Nat,
    'requiredSkills' : IDL.Text,
    'location' : IDL.Text,
  });
  const UpsertEmployerInput = IDL.Record({
    'websiteUrl' : IDL.Text,
    'description' : IDL.Text,
    'companyName' : IDL.Text,
  });
  const UpsertJobSeekerInput = IDL.Record({
    'bio' : IDL.Text,
    'yearsOfExperience' : IDL.Nat,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'phone' : IDL.Text,
    'skills' : IDL.Text,
  });
  
  return IDL.Service({
    'adminGetStats' : IDL.Func(
        [],
        [
          IDL.Record({
            'totalEmployers' : IDL.Nat,
            'totalJobSeekers' : IDL.Nat,
            'totalJobs' : IDL.Nat,
            'totalApplications' : IDL.Nat,
          }),
        ],
        [],
      ),
    'adminListEmployers' : IDL.Func([], [IDL.Vec(EmployerProfilePublic)], []),
    'adminListJobSeekers' : IDL.Func([], [IDL.Vec(JobSeekerProfilePublic)], []),
    'createJob' : IDL.Func([CreateJobInput], [JobId], []),
    'deleteJob' : IDL.Func([JobId], [], []),
    'getEmployerProfile' : IDL.Func(
        [UserId],
        [IDL.Opt(EmployerProfilePublic)],
        ['query'],
      ),
    'getJob' : IDL.Func([JobId], [IDL.Opt(JobPublic)], ['query']),
    'getJobSeekerProfile' : IDL.Func(
        [UserId],
        [IDL.Opt(JobSeekerProfilePublic)],
        ['query'],
      ),
    'getMyEmployerProfile' : IDL.Func(
        [],
        [IDL.Opt(EmployerProfilePublic)],
        ['query'],
      ),
    'getMyJobSeekerProfile' : IDL.Func(
        [],
        [IDL.Opt(JobSeekerProfilePublic)],
        ['query'],
      ),
    'getMyUserType' : IDL.Func([], [IDL.Opt(UserType)], ['query']),
    'getUserType' : IDL.Func([UserId], [IDL.Opt(UserType)], ['query']),
    'hasApplied' : IDL.Func([JobId], [IDL.Bool], ['query']),
    'listApplicationsForJob' : IDL.Func(
        [JobId],
        [IDL.Vec(ApplicationPublic)],
        ['query'],
      ),
    'listApplicationsForMyJobs' : IDL.Func(
        [],
        [IDL.Vec(ApplicationPublic)],
        ['query'],
      ),
    'listMyApplications' : IDL.Func(
        [],
        [IDL.Vec(ApplicationPublic)],
        ['query'],
      ),
    'listMyJobs' : IDL.Func([], [IDL.Vec(JobPublic)], ['query']),
    'listOpenJobs' : IDL.Func([], [IDL.Vec(JobPublic)], ['query']),
    'setUserType' : IDL.Func([UserType], [], []),
    'submitApplication' : IDL.Func(
        [SubmitApplicationInput],
        [ApplicationId],
        [],
      ),
    'toggleJobStatus' : IDL.Func([JobId], [], []),
    'updateApplicationStatus' : IDL.Func(
        [ApplicationId, ApplicationStatus],
        [],
        [],
      ),
    'updateJob' : IDL.Func([UpdateJobInput], [], []),
    'upsertEmployerProfile' : IDL.Func([UpsertEmployerInput], [], []),
    'upsertJobSeekerProfile' : IDL.Func([UpsertJobSeekerInput], [], []),
    'withdrawApplication' : IDL.Func([ApplicationId], [], []),
  });
};

export const init = ({ IDL }) => { return []; };