/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface CreateJobInput {
    title: string;
    jobType: JobType;
    description: string;
    salaryMax: bigint;
    salaryMin: bigint;
    requiredSkills: string;
    location: string;
}
export interface UpdateJobInput {
    id: JobId;
    title: string;
    jobType: JobType;
    description: string;
    salaryMax: bigint;
    salaryMin: bigint;
    requiredSkills: string;
    location: string;
}
export type Timestamp = bigint;
export interface SubmitApplicationInput {
    jobId: JobId;
    coverLetter: string;
}
export interface EmployerProfilePublic {
    id: UserId;
    websiteUrl: string;
    createdAt: Timestamp;
    description: string;
    companyName: string;
}
export type JobId = bigint;
export interface UpsertEmployerInput {
    websiteUrl: string;
    description: string;
    companyName: string;
}
export interface UpsertJobSeekerInput {
    bio: string;
    yearsOfExperience: bigint;
    name: string;
    email: string;
    phone: string;
    skills: string;
}
export type UserId = Principal;
export interface JobSeekerProfilePublic {
    id: UserId;
    bio: string;
    yearsOfExperience: bigint;
    name: string;
    createdAt: Timestamp;
    email: string;
    phone: string;
    skills: string;
}
export interface JobPublic {
    id: JobId;
    status: JobStatus;
    title: string;
    postedAt: Timestamp;
    jobType: JobType;
    description: string;
    employerId: UserId;
    salaryMax: bigint;
    salaryMin: bigint;
    requiredSkills: string;
    location: string;
}
export interface ApplicationPublic {
    id: ApplicationId;
    status: ApplicationStatus;
    appliedAt: Timestamp;
    applicantId: UserId;
    jobId: JobId;
    coverLetter: string;
}
export type ApplicationId = bigint;
export enum ApplicationStatus {
    Viewed = "Viewed",
    Rejected = "Rejected",
    Accepted = "Accepted",
    Pending = "Pending"
}
export enum JobStatus {
    Open = "Open",
    Closed = "Closed"
}
export enum JobType {
    PartTime = "PartTime",
    Remote = "Remote",
    FullTime = "FullTime"
}
export enum UserType {
    JobSeeker = "JobSeeker",
    Employer = "Employer"
}
export interface backendInterface {
    adminGetStats(): Promise<{
        totalEmployers: bigint;
        totalJobSeekers: bigint;
        totalJobs: bigint;
        totalApplications: bigint;
    }>;
    adminListEmployers(): Promise<Array<EmployerProfilePublic>>;
    adminListJobSeekers(): Promise<Array<JobSeekerProfilePublic>>;
    createJob(input: CreateJobInput): Promise<JobId>;
    deleteJob(jobId: JobId): Promise<void>;
    getEmployerProfile(userId: UserId): Promise<EmployerProfilePublic | null>;
    getJob(jobId: JobId): Promise<JobPublic | null>;
    getJobSeekerProfile(userId: UserId): Promise<JobSeekerProfilePublic | null>;
    getMyEmployerProfile(): Promise<EmployerProfilePublic | null>;
    getMyJobSeekerProfile(): Promise<JobSeekerProfilePublic | null>;
    getMyUserType(): Promise<UserType | null>;
    getUserType(userId: UserId): Promise<UserType | null>;
    hasApplied(jobId: JobId): Promise<boolean>;
    listApplicationsForJob(jobId: JobId): Promise<Array<ApplicationPublic>>;
    listApplicationsForMyJobs(): Promise<Array<ApplicationPublic>>;
    listMyApplications(): Promise<Array<ApplicationPublic>>;
    listMyJobs(): Promise<Array<JobPublic>>;
    listOpenJobs(): Promise<Array<JobPublic>>;
    setUserType(userType: UserType): Promise<void>;
    submitApplication(input: SubmitApplicationInput): Promise<ApplicationId>;
    toggleJobStatus(jobId: JobId): Promise<void>;
    updateApplicationStatus(applicationId: ApplicationId, status: ApplicationStatus): Promise<void>;
    updateJob(input: UpdateJobInput): Promise<void>;
    upsertEmployerProfile(input: UpsertEmployerInput): Promise<void>;
    upsertJobSeekerProfile(input: UpsertJobSeekerInput): Promise<void>;
    withdrawApplication(applicationId: ApplicationId): Promise<void>;
}
import type { ApplicationId as _ApplicationId, ApplicationPublic as _ApplicationPublic, ApplicationStatus as _ApplicationStatus, CreateJobInput as _CreateJobInput, EmployerProfilePublic as _EmployerProfilePublic, JobId as _JobId, JobPublic as _JobPublic, JobSeekerProfilePublic as _JobSeekerProfilePublic, JobStatus as _JobStatus, JobType as _JobType, Timestamp as _Timestamp, UpdateJobInput as _UpdateJobInput, UserId as _UserId, UserType as _UserType } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async adminGetStats(): Promise<{
        totalEmployers: bigint;
        totalJobSeekers: bigint;
        totalJobs: bigint;
        totalApplications: bigint;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.adminGetStats();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminGetStats();
            return result;
        }
    }
    async adminListEmployers(): Promise<Array<EmployerProfilePublic>> {
        if (this.processError) {
            try {
                const result = await this.actor.adminListEmployers();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminListEmployers();
            return result;
        }
    }
    async adminListJobSeekers(): Promise<Array<JobSeekerProfilePublic>> {
        if (this.processError) {
            try {
                const result = await this.actor.adminListJobSeekers();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminListJobSeekers();
            return result;
        }
    }
    async createJob(arg0: CreateJobInput): Promise<JobId> {
        if (this.processError) {
            try {
                const result = await this.actor.createJob(to_candid_CreateJobInput_n1(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createJob(to_candid_CreateJobInput_n1(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async deleteJob(arg0: JobId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteJob(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteJob(arg0);
            return result;
        }
    }
    async getEmployerProfile(arg0: UserId): Promise<EmployerProfilePublic | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getEmployerProfile(arg0);
                return from_candid_opt_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getEmployerProfile(arg0);
            return from_candid_opt_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async getJob(arg0: JobId): Promise<JobPublic | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getJob(arg0);
                return from_candid_opt_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getJob(arg0);
            return from_candid_opt_n6(this._uploadFile, this._downloadFile, result);
        }
    }
    async getJobSeekerProfile(arg0: UserId): Promise<JobSeekerProfilePublic | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getJobSeekerProfile(arg0);
                return from_candid_opt_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getJobSeekerProfile(arg0);
            return from_candid_opt_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyEmployerProfile(): Promise<EmployerProfilePublic | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyEmployerProfile();
                return from_candid_opt_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyEmployerProfile();
            return from_candid_opt_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyJobSeekerProfile(): Promise<JobSeekerProfilePublic | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyJobSeekerProfile();
                return from_candid_opt_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyJobSeekerProfile();
            return from_candid_opt_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyUserType(): Promise<UserType | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyUserType();
                return from_candid_opt_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyUserType();
            return from_candid_opt_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserType(arg0: UserId): Promise<UserType | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserType(arg0);
                return from_candid_opt_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserType(arg0);
            return from_candid_opt_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async hasApplied(arg0: JobId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.hasApplied(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.hasApplied(arg0);
            return result;
        }
    }
    async listApplicationsForJob(arg0: JobId): Promise<Array<ApplicationPublic>> {
        if (this.processError) {
            try {
                const result = await this.actor.listApplicationsForJob(arg0);
                return from_candid_vec_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listApplicationsForJob(arg0);
            return from_candid_vec_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async listApplicationsForMyJobs(): Promise<Array<ApplicationPublic>> {
        if (this.processError) {
            try {
                const result = await this.actor.listApplicationsForMyJobs();
                return from_candid_vec_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listApplicationsForMyJobs();
            return from_candid_vec_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async listMyApplications(): Promise<Array<ApplicationPublic>> {
        if (this.processError) {
            try {
                const result = await this.actor.listMyApplications();
                return from_candid_vec_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listMyApplications();
            return from_candid_vec_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async listMyJobs(): Promise<Array<JobPublic>> {
        if (this.processError) {
            try {
                const result = await this.actor.listMyJobs();
                return from_candid_vec_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listMyJobs();
            return from_candid_vec_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async listOpenJobs(): Promise<Array<JobPublic>> {
        if (this.processError) {
            try {
                const result = await this.actor.listOpenJobs();
                return from_candid_vec_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listOpenJobs();
            return from_candid_vec_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async setUserType(arg0: UserType): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setUserType(to_candid_UserType_n23(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setUserType(to_candid_UserType_n23(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async submitApplication(arg0: SubmitApplicationInput): Promise<ApplicationId> {
        if (this.processError) {
            try {
                const result = await this.actor.submitApplication(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitApplication(arg0);
            return result;
        }
    }
    async toggleJobStatus(arg0: JobId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.toggleJobStatus(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.toggleJobStatus(arg0);
            return result;
        }
    }
    async updateApplicationStatus(arg0: ApplicationId, arg1: ApplicationStatus): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateApplicationStatus(arg0, to_candid_ApplicationStatus_n25(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateApplicationStatus(arg0, to_candid_ApplicationStatus_n25(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateJob(arg0: UpdateJobInput): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateJob(to_candid_UpdateJobInput_n27(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateJob(to_candid_UpdateJobInput_n27(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async upsertEmployerProfile(arg0: UpsertEmployerInput): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.upsertEmployerProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.upsertEmployerProfile(arg0);
            return result;
        }
    }
    async upsertJobSeekerProfile(arg0: UpsertJobSeekerInput): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.upsertJobSeekerProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.upsertJobSeekerProfile(arg0);
            return result;
        }
    }
    async withdrawApplication(arg0: ApplicationId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.withdrawApplication(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.withdrawApplication(arg0);
            return result;
        }
    }
}
function from_candid_ApplicationPublic_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ApplicationPublic): ApplicationPublic {
    return from_candid_record_n19(_uploadFile, _downloadFile, value);
}
function from_candid_ApplicationStatus_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ApplicationStatus): ApplicationStatus {
    return from_candid_variant_n21(_uploadFile, _downloadFile, value);
}
function from_candid_JobPublic_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _JobPublic): JobPublic {
    return from_candid_record_n8(_uploadFile, _downloadFile, value);
}
function from_candid_JobStatus_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _JobStatus): JobStatus {
    return from_candid_variant_n10(_uploadFile, _downloadFile, value);
}
function from_candid_JobType_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _JobType): JobType {
    return from_candid_variant_n12(_uploadFile, _downloadFile, value);
}
function from_candid_UserType_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserType): UserType {
    return from_candid_variant_n16(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_JobSeekerProfilePublic]): JobSeekerProfilePublic | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserType]): UserType | null {
    return value.length === 0 ? null : from_candid_UserType_n15(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_EmployerProfilePublic]): EmployerProfilePublic | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_JobPublic]): JobPublic | null {
    return value.length === 0 ? null : from_candid_JobPublic_n7(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _ApplicationId;
    status: _ApplicationStatus;
    appliedAt: _Timestamp;
    applicantId: _UserId;
    jobId: _JobId;
    coverLetter: string;
}): {
    id: ApplicationId;
    status: ApplicationStatus;
    appliedAt: Timestamp;
    applicantId: UserId;
    jobId: JobId;
    coverLetter: string;
} {
    return {
        id: value.id,
        status: from_candid_ApplicationStatus_n20(_uploadFile, _downloadFile, value.status),
        appliedAt: value.appliedAt,
        applicantId: value.applicantId,
        jobId: value.jobId,
        coverLetter: value.coverLetter
    };
}
function from_candid_record_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _JobId;
    status: _JobStatus;
    title: string;
    postedAt: _Timestamp;
    jobType: _JobType;
    description: string;
    employerId: _UserId;
    salaryMax: bigint;
    salaryMin: bigint;
    requiredSkills: string;
    location: string;
}): {
    id: JobId;
    status: JobStatus;
    title: string;
    postedAt: Timestamp;
    jobType: JobType;
    description: string;
    employerId: UserId;
    salaryMax: bigint;
    salaryMin: bigint;
    requiredSkills: string;
    location: string;
} {
    return {
        id: value.id,
        status: from_candid_JobStatus_n9(_uploadFile, _downloadFile, value.status),
        title: value.title,
        postedAt: value.postedAt,
        jobType: from_candid_JobType_n11(_uploadFile, _downloadFile, value.jobType),
        description: value.description,
        employerId: value.employerId,
        salaryMax: value.salaryMax,
        salaryMin: value.salaryMin,
        requiredSkills: value.requiredSkills,
        location: value.location
    };
}
function from_candid_variant_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Open: null;
} | {
    Closed: null;
}): JobStatus {
    return "Open" in value ? JobStatus.Open : "Closed" in value ? JobStatus.Closed : value;
}
function from_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    PartTime: null;
} | {
    Remote: null;
} | {
    FullTime: null;
}): JobType {
    return "PartTime" in value ? JobType.PartTime : "Remote" in value ? JobType.Remote : "FullTime" in value ? JobType.FullTime : value;
}
function from_candid_variant_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    JobSeeker: null;
} | {
    Employer: null;
}): UserType {
    return "JobSeeker" in value ? UserType.JobSeeker : "Employer" in value ? UserType.Employer : value;
}
function from_candid_variant_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Viewed: null;
} | {
    Rejected: null;
} | {
    Accepted: null;
} | {
    Pending: null;
}): ApplicationStatus {
    return "Viewed" in value ? ApplicationStatus.Viewed : "Rejected" in value ? ApplicationStatus.Rejected : "Accepted" in value ? ApplicationStatus.Accepted : "Pending" in value ? ApplicationStatus.Pending : value;
}
function from_candid_vec_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ApplicationPublic>): Array<ApplicationPublic> {
    return value.map((x)=>from_candid_ApplicationPublic_n18(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_JobPublic>): Array<JobPublic> {
    return value.map((x)=>from_candid_JobPublic_n7(_uploadFile, _downloadFile, x));
}
function to_candid_ApplicationStatus_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ApplicationStatus): _ApplicationStatus {
    return to_candid_variant_n26(_uploadFile, _downloadFile, value);
}
function to_candid_CreateJobInput_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CreateJobInput): _CreateJobInput {
    return to_candid_record_n2(_uploadFile, _downloadFile, value);
}
function to_candid_JobType_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: JobType): _JobType {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_UpdateJobInput_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UpdateJobInput): _UpdateJobInput {
    return to_candid_record_n28(_uploadFile, _downloadFile, value);
}
function to_candid_UserType_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserType): _UserType {
    return to_candid_variant_n24(_uploadFile, _downloadFile, value);
}
function to_candid_record_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    title: string;
    jobType: JobType;
    description: string;
    salaryMax: bigint;
    salaryMin: bigint;
    requiredSkills: string;
    location: string;
}): {
    title: string;
    jobType: _JobType;
    description: string;
    salaryMax: bigint;
    salaryMin: bigint;
    requiredSkills: string;
    location: string;
} {
    return {
        title: value.title,
        jobType: to_candid_JobType_n3(_uploadFile, _downloadFile, value.jobType),
        description: value.description,
        salaryMax: value.salaryMax,
        salaryMin: value.salaryMin,
        requiredSkills: value.requiredSkills,
        location: value.location
    };
}
function to_candid_record_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: JobId;
    title: string;
    jobType: JobType;
    description: string;
    salaryMax: bigint;
    salaryMin: bigint;
    requiredSkills: string;
    location: string;
}): {
    id: _JobId;
    title: string;
    jobType: _JobType;
    description: string;
    salaryMax: bigint;
    salaryMin: bigint;
    requiredSkills: string;
    location: string;
} {
    return {
        id: value.id,
        title: value.title,
        jobType: to_candid_JobType_n3(_uploadFile, _downloadFile, value.jobType),
        description: value.description,
        salaryMax: value.salaryMax,
        salaryMin: value.salaryMin,
        requiredSkills: value.requiredSkills,
        location: value.location
    };
}
function to_candid_variant_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserType): {
    JobSeeker: null;
} | {
    Employer: null;
} {
    return value == UserType.JobSeeker ? {
        JobSeeker: null
    } : value == UserType.Employer ? {
        Employer: null
    } : value;
}
function to_candid_variant_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ApplicationStatus): {
    Viewed: null;
} | {
    Rejected: null;
} | {
    Accepted: null;
} | {
    Pending: null;
} {
    return value == ApplicationStatus.Viewed ? {
        Viewed: null
    } : value == ApplicationStatus.Rejected ? {
        Rejected: null
    } : value == ApplicationStatus.Accepted ? {
        Accepted: null
    } : value == ApplicationStatus.Pending ? {
        Pending: null
    } : value;
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: JobType): {
    PartTime: null;
} | {
    Remote: null;
} | {
    FullTime: null;
} {
    return value == JobType.PartTime ? {
        PartTime: null
    } : value == JobType.Remote ? {
        Remote: null
    } : value == JobType.FullTime ? {
        FullTime: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
